id: A9FD1DE8C
title: Samantabhadra
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:08:25.219003
  last_modified_at: 2022-03-01 22:08:25.219031
